### ISSUE TITLE
Request to delete server within program

### ISSUE THREAD

**Issue by JustinBenedick** [Drifter321/admintool#11]
Could we ge an option to delete the saved servers within the program, as of right now it requires to shut down SAT and edit the settings.ini file.

**Comment by psychonic** [comment]
Click the server and push the Delete key on the keyboard.

-- 
Nicholas Hastings

**Comment by JustinBenedick** [comment]
Any chance you can add it to the context menu when you right click on the server?

**Comment by Drifter321** [comment]
This already exists in the master branch.
