### ISSUE TITLE
"Already authenticated" even after connection was lost.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Drifter321/admintool#12]
So, the title explains my issue pretty much.
After i lose connection to the server (be it internet connection problem or server restart), i'm getting that "Already authenticated" error when attempting to login to rcon (i have to restart the program and reconnect to all my servers again - it's very annoying to restart each time this happens).

**Comment by Drifter321** [comment]
What happens if you dont hit login and try to send a command?

**Comment by YuRaNnNzZZ** [comment]
Nothing happens, server just don't respond to the command.

**Comment by Drifter321** [comment]
Cant seem to replicate this. As soon as the socket gets disconnected it is marked as not authed and next command or login attempt reauths.
