### ISSUE TITLE
"get log" not working.

### ISSUE THREAD

**Issue by VolKanThe1** [Drifter321/admintool#18]
I've been using the admintool for some time now and all of a sudden the "get log" button just stopped working.

I was getting this output in RCON:

L 11/18/2018 - 21:54:39: Log file closed.
Server logging data to file logs/L1118006.log
L 11/18/2018 - 21:54:40: Log file started (file "logs/L1118006.log") (game "/servers/retroeu02/tf") (version "4783668")
logaddress_add: 80.200.20.223:50882 is already in the list

I tried to logaddress_del 80.200.20.223:50882 and then retried: 

Server logging enabled.
L 11/18/2018 - 22:18:50: Log file closed.
Server logging data to file logs/L1118010.log
L 11/18/2018 - 22:18:51: Log file started (file "logs/L1118010.log") (game "/servers/retroeu02/tf") (version "4783668")
logaddress_add: 80.200.20.223:50882

However I'm still not getting any log

**Comment by Drifter321** [comment]
Is the server local?

**Comment by VolKanThe1** [comment]
Remote

**Comment by Drifter321** [comment]
I cant seem to replicate it for servers with external ip's. However, did experience it with local servers.

**Comment by VolKanThe1** [comment]
Yeah I saw a similar issue some guy posted, but his was local too.

Thing is, I haven't changed any settings, it just stopped showing logs all of a sudden one day

**Comment by Drifter321** [comment]
Actually, I was using an outdated version. Local issues are fixed in master already. If it worked previously and you didnt update SAT I doubt its related to SAT.

**Comment by VolKanThe1** [comment]
Hmm, what could be causing it you think?
I don't recall changing anything at all really

Incase it sheds some light, here's a side by side (HLSW & SAT) 
![963999615fa68ddc21ac605fdaf3de1f](https://user-images.githubusercontent.com/45152531/48792888-b0135600-ecf5-11e8-8886-8ca9207085d0.png)

**Comment by Drifter321** [comment]
The port that is used by SAT is used by something else or blocked would be my guess. You can try deleting the port in the config file for it to pick/create another.

**Comment by VolKanThe1** [comment]
Huh, that worked. Could've sworn I wiped it previously. Thanks man
