### ISSUE TITLE
Not able to login with rcon password

### ISSUE THREAD

**Issue by Hgmoa** [Drifter321/admintool#2]
Hi, I have a csgo server for a team already setup and I can access it both from lan and from internet, and im trying to use your tool to ease up a bit the managament of the server.
But I´m having a problem when trying to login after entering the rcon password I have for my server, the password does not have spaces nor underscores, simple one word, but clicking on login or get log does nothing...
Any help?
Thx in advance and this tool looks promising!

(English is not my first language, sry)

**Comment by Drifter321** [comment]
If you dont receive a failed to authentic or a welcome message it typically means the server never responded to the rcon login request. Make sure that you have -usercon in the launch parameters.

**Comment by Hgmoa** [comment]
Strangely restarting the computer the server is sitting on fixed the error... I was able to access it from ingame console but not from your tool, strange
