### ISSUE TITLE
Win version cannot be used

### ISSUE THREAD

**Issue by fdxx** [Drifter321/admintool#24]
Steps to reproduce:
1. Download Actions SAT-win-69fe266 version.
2. Open the software, wait for a few seconds, and then the log listening message appears.
![Snipaste_2021-07-04_01-16-34](https://user-images.githubusercontent.com/44993923/124362079-7fde1300-dc65-11eb-916d-bb9835498748.jpg)

3. Click ok, Software crashes and exits.

**Comment by BrutalCSEjziponken** [comment]
I get the same problem.

**Comment by Gimperfied** [comment]
same issue

SAT-win-114d301

**Comment by DarkCurseBreaker** [comment]
### I have the same issue on the following versions:

SAT-win-114d301
SAT-win-69fe266
SAT-win-c76913f

### Steps to reproduce:

1. Run the executable SourceAdminTool.exe
2. Wait for a few seconds to a minute
3. Log Handler dialog pops up with the message, Listening on: xxx.xxx.xxx.xxx:port
4. Click OK

### Results

Upon clicking OK, the program closes (Image 1)

### Logs and other info

I couldn't find any logs my folder looks like Image 2.

My settings .ini looks like Image 3

XXX.XXX.XXX.XXX:port corresponds to my _**public ip**_ in the Log Handler dialog. The port here is the same port as logPort in settings.ini

XXX.XXX.XXX.XXX:port corresponds to my TF2 dedicated server _**local ip**_ in settings.ini

### Images

Image 1
![Issue](https://user-images.githubusercontent.com/63136603/134863657-e692614a-fc53-4909-810e-f0e3ede8e6ce.png)

Image 2
![image](https://user-images.githubusercontent.com/63136603/134863876-85bc9b20-ebae-475a-b919-00cf8ad25b01.png)

Image 3
![Issue 3](https://user-images.githubusercontent.com/63136603/134865017-f6dda097-0fe7-4521-a4cb-391d7bd74926.png)

**Comment by peace-maker** [comment]
I don't have time to properly debug this soon :( It appears to be some heap corruption, but I've never used something like ASAN on Windows + QT too. It might be some mismatch of the libmaxmind binary, because I didn't rebuild for windows or mac, but still updated the headers in 3acc51932f335ef9aabfb66af727551b3c99604a. Maybe updating the project to a newer QT for building in Github Actions required more additional changes?

Would be great if someone could debug this mess.

**Comment by jankovalski** [comment]
I have the issue on Windows and I just compiled it on Linux. The same issue appears. The window closes after clicking OK on the Log Handler dialog.

**Comment by jankovalski** [comment]
I just commented out the 3 lines containing "pLogHandler" in mainwindow.cpp and that solved the issue. I can see the servers and do things through rcon. How is this loghandler important?
