### ISSUE TITLE
Executing rcon commands twice after login

### ISSUE THREAD

**Issue by peace-maker** [Drifter321/admintool#3]
When the rcon connection was closed after a while due to not sending any commands, sending a new command causes it to login properly, but sends the command twice after that.

```
] sm plugins load spawnpoints
Welcome user! 
L 02/24/2017 - 04:49:17: rcon from "1.2.3.4:55426": command "echo Welcome user!"
[SM] Loaded plugin spawnpoints.smx successfully.
L 02/24/2017 - 04:49:17: rcon from "1.2.3.4:55426": command "sm plugins load spawnpoints"
[SM] Plugin spawnpoints.smx is already loaded.
L 02/24/2017 - 04:49:17: rcon from "1.2.3.4:55426": command "sm plugins load spawnpoints"
```

**Comment by Drifter321** [comment]
Interesting, I had a quick look and cant see why it would be adding it to the queue twice. I see a possible issue but still didn't see why it would run twice. I'll have a better look once i merge the other branch as it changes lots of code.

**Comment by Drifter321** [comment]
Fixed in master.
