### ISSUE TITLE
AdminTool not querying servers (for CS:GO with the latest update)

### ISSUE THREAD

**Issue by SpirTBBX** [Drifter321/admintool#32]
As the new CS:GO update was released, the variables's names for hostname, map, players, maxplayers, etc... changed.

Therefore the app requires an update to address this issue.
Is there any way that I can fix it on my own?
If yes, what is required to change?

**Comment by peace-maker** [comment]
Could you provide more details of whats broken please? Querying CSGO servers seems to work for me.

Are you running the latest snapshot?
https://nightly.link/Drifter321/admintool/workflows/build/master

**Comment by tk1114632** [comment]
> Could you provide more details of whats broken please? Querying CSGO servers seems to work for me.
> 
> Are you running the latest snapshot? https://nightly.link/Drifter321/admintool/workflows/build/master

Hi, the nightly link seems unavailable now, is there any other way to download the lastest build? Thanks.

**Comment by peace-maker** [comment]
I've triggered the actions workflow again. py7zr updated it's dependencies which magically propagated to here for a fix. OSS is great 😃
