### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by jffz** [Drifter321/admintool#7]
- Add `ip` field in server array UI
- Option to disable count bots as players

**Comment by Drifter321** [comment]
Not sure what you mean for the first one. As for the second one, no.

**Comment by jffz** [comment]
for the second, i mean having them in a separate count to directly see if players are bots or not.

About the first one:
https://gyazo.com/fecfb03383e5d1faa267f3af574481b3

Add IP field in here to allow sort by node.

**Comment by Drifter321** [comment]
The bots is in parentheses if you cant do simple math I cant help you. I dont want to clutter the ui so no on the first as well.

**Comment by jffz** [comment]
Readability has nothing to do with maths it's just better for daily use.

If you can't understand that would be helpful for people with a lot of servers I cant help you.
